//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 02:54:52 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://order.nure.ua/entity/")
package ua.nure.order.entity;
