
package ua.nure.order.server.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Thu Feb 11 15:07:28 EET 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "addBook", namespace = "http://service.server.order.nure.ua/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addBook", namespace = "http://service.server.order.nure.ua/")

public class AddBook {

    @XmlElement(name = "book")
    private ua.nure.order.entity.book.Book book;

    public ua.nure.order.entity.book.Book getBook() {
        return this.book;
    }

    public void setBook(ua.nure.order.entity.book.Book newBook)  {
        this.book = newBook;
    }

}

