
package ua.nure.order.server.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Thu Feb 11 15:07:28 EET 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "addBookResponse", namespace = "http://service.server.order.nure.ua/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addBookResponse", namespace = "http://service.server.order.nure.ua/")

public class AddBookResponse {

    @XmlElement(name = "return")
    private ua.nure.order.entity.book.Book _return;

    public ua.nure.order.entity.book.Book getReturn() {
        return this._return;
    }

    public void setReturn(ua.nure.order.entity.book.Book new_return)  {
        this._return = new_return;
    }

}

