
package ua.nure.order.server.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Thu Feb 11 15:07:28 EET 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "listBooks", namespace = "http://service.server.order.nure.ua/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listBooks", namespace = "http://service.server.order.nure.ua/")

public class ListBooks {

    @XmlElement(name = "pattern")
    private java.lang.String pattern;

    public java.lang.String getPattern() {
        return this.pattern;
    }

    public void setPattern(java.lang.String newPattern)  {
        this.pattern = newPattern;
    }

}

