//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 12:37:22 PM EET 
//


package org.example.integers;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IntType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="tInteger" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tLong" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="tInt" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tShort" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="tByte" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="tPositiveInteger" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="tNonPositiveInteger" type="{http://www.w3.org/2001/XMLSchema}nonPositiveInteger"/>
 *         &lt;element name="tNegativeInteger" type="{http://www.w3.org/2001/XMLSchema}negativeInteger"/>
 *         &lt;element name="tNonNegativeInteger" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="uLong" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="uInt" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="uShort" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="uByte" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntType", propOrder = {

})
public class IntType {

    @XmlElement(required = true)
    protected BigInteger tInteger;
    protected long tLong;
    protected int tInt;
    protected short tShort;
    protected byte tByte;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger tPositiveInteger;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonPositiveInteger")
    protected BigInteger tNonPositiveInteger;
    @XmlElement(required = true)
    @XmlSchemaType(name = "negativeInteger")
    protected BigInteger tNegativeInteger;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger tNonNegativeInteger;
    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger uLong;
    @XmlSchemaType(name = "unsignedInt")
    protected long uInt;
    @XmlSchemaType(name = "unsignedShort")
    protected int uShort;
    @XmlSchemaType(name = "unsignedByte")
    protected short uByte;

    /**
     * Gets the value of the tInteger property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTInteger() {
        return tInteger;
    }

    /**
     * Sets the value of the tInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTInteger(BigInteger value) {
        this.tInteger = value;
    }

    /**
     * Gets the value of the tLong property.
     * 
     */
    public long getTLong() {
        return tLong;
    }

    /**
     * Sets the value of the tLong property.
     * 
     */
    public void setTLong(long value) {
        this.tLong = value;
    }

    /**
     * Gets the value of the tInt property.
     * 
     */
    public int getTInt() {
        return tInt;
    }

    /**
     * Sets the value of the tInt property.
     * 
     */
    public void setTInt(int value) {
        this.tInt = value;
    }

    /**
     * Gets the value of the tShort property.
     * 
     */
    public short getTShort() {
        return tShort;
    }

    /**
     * Sets the value of the tShort property.
     * 
     */
    public void setTShort(short value) {
        this.tShort = value;
    }

    /**
     * Gets the value of the tByte property.
     * 
     */
    public byte getTByte() {
        return tByte;
    }

    /**
     * Sets the value of the tByte property.
     * 
     */
    public void setTByte(byte value) {
        this.tByte = value;
    }

    /**
     * Gets the value of the tPositiveInteger property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTPositiveInteger() {
        return tPositiveInteger;
    }

    /**
     * Sets the value of the tPositiveInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTPositiveInteger(BigInteger value) {
        this.tPositiveInteger = value;
    }

    /**
     * Gets the value of the tNonPositiveInteger property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTNonPositiveInteger() {
        return tNonPositiveInteger;
    }

    /**
     * Sets the value of the tNonPositiveInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTNonPositiveInteger(BigInteger value) {
        this.tNonPositiveInteger = value;
    }

    /**
     * Gets the value of the tNegativeInteger property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTNegativeInteger() {
        return tNegativeInteger;
    }

    /**
     * Sets the value of the tNegativeInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTNegativeInteger(BigInteger value) {
        this.tNegativeInteger = value;
    }

    /**
     * Gets the value of the tNonNegativeInteger property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTNonNegativeInteger() {
        return tNonNegativeInteger;
    }

    /**
     * Sets the value of the tNonNegativeInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTNonNegativeInteger(BigInteger value) {
        this.tNonNegativeInteger = value;
    }

    /**
     * Gets the value of the uLong property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getULong() {
        return uLong;
    }

    /**
     * Sets the value of the uLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setULong(BigInteger value) {
        this.uLong = value;
    }

    /**
     * Gets the value of the uInt property.
     * 
     */
    public long getUInt() {
        return uInt;
    }

    /**
     * Sets the value of the uInt property.
     * 
     */
    public void setUInt(long value) {
        this.uInt = value;
    }

    /**
     * Gets the value of the uShort property.
     * 
     */
    public int getUShort() {
        return uShort;
    }

    /**
     * Sets the value of the uShort property.
     * 
     */
    public void setUShort(int value) {
        this.uShort = value;
    }

    /**
     * Gets the value of the uByte property.
     * 
     */
    public short getUByte() {
        return uByte;
    }

    /**
     * Sets the value of the uByte property.
     * 
     */
    public void setUByte(short value) {
        this.uByte = value;
    }

}
