//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 08:22:14 AM EET 
//


package ua.nure.order.entity.order;

import java.util.Map;
import java.util.Map.Entry;

import ua.nure.order.entity.Product;


public class Order<T extends Product> extends Product {

	private static final long serialVersionUID = -2130624107521935696L;
	protected Map<T, Integer> items;
    
	public Order() {
		super();
	}

	public Order(Map<T, Integer> items) {
		super();
		this.items = items;
	}

	public Order(Integer id, Map<T, Integer> items) {
		super(id);
		this.items = items;
	}
	
	public Map<T, Integer> getItems() {
		return items;
	}

	public void setItems(Map<T, Integer> items) {
		this.items = items;
	}

	@Override
	public double getPrice() {
		double total = 0.;
		for (Entry<T, Integer> e : items.entrySet()) {
			total += e.getKey().getPrice();
		}
		return total;
	}
}
