
package ua.nure.itech.jaxws.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloService", targetNamespace = "http://service.jaxws.itech.nure.ua/", wsdlLocation = "META-INF/wsdl/hello.wsdl")
public class HelloService
    extends Service
{

    private final static URL HELLOSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSERVICE_EXCEPTION;
    private final static QName HELLOSERVICE_QNAME = new QName("http://service.jaxws.itech.nure.ua/", "HelloService");

    static {
        HELLOSERVICE_WSDL_LOCATION = ua.nure.itech.jaxws.service.HelloService.class.getClassLoader().getResource("META-INF/wsdl/hello.wsdl");
        WebServiceException e = null;
        if (HELLOSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/hello.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        HELLOSERVICE_EXCEPTION = e;
    }

    public HelloService() {
        super(__getWsdlLocation(), HELLOSERVICE_QNAME);
    }

    public HelloService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERVICE_QNAME, features);
    }

    public HelloService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERVICE_QNAME);
    }

    public HelloService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERVICE_QNAME, features);
    }

    public HelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloMessenger
     */
    @WebEndpoint(name = "HelloPort")
    public HelloMessenger getHelloPort() {
        return super.getPort(new QName("http://service.jaxws.itech.nure.ua/", "HelloPort"), HelloMessenger.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloMessenger
     */
    @WebEndpoint(name = "HelloPort")
    public HelloMessenger getHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jaxws.itech.nure.ua/", "HelloPort"), HelloMessenger.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERVICE_EXCEPTION!= null) {
            throw HELLOSERVICE_EXCEPTION;
        }
        return HELLOSERVICE_WSDL_LOCATION;
    }

}
