
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ua.nure.order.server.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2016-02-17T09:48:13.801+02:00
 * Generated source version: 3.0.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "BookService",
                      portName = "BookServicePort",
                      targetNamespace = "http://service.server.order.nure.ua/",
                      wsdlLocation = "http://localhost:8080/ws/services/BookService?wsdl",
                      endpointInterface = "ua.nure.order.server.service.BookService")
                      
public class BookServicePortImpl implements BookService {

    private static final Logger LOG = Logger.getLogger(BookServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see ua.nure.order.server.service.BookService#deleteBook(int  id )*
     */
    public ua.nure.order.entity.book.Book deleteBook(int id) throws DAOException_Exception    { 
        LOG.info("Executing operation deleteBook");
        System.out.println(id);
        try {
            ua.nure.order.entity.book.Book _return = new ua.nure.order.entity.book.Book();
            _return.setId(Integer.valueOf(1135237878));
            _return.setTitle("Title-596480667");
            java.util.List<java.lang.String> _returnAuthor = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAuthorVal1 = "_returnAuthorVal2104461315";
            _returnAuthor.add(_returnAuthorVal1);
            _return.getAuthor().addAll(_returnAuthor);
            _return.setIsbn("Isbn-1967500976");
            _return.setPrice(0.4317089598018756);
            ua.nure.order.entity.book.Category _returnCategory = ua.nure.order.entity.book.Category.ACTION;
            _return.setCategory(_returnCategory);
            _return.setCount(208924561);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DAOException_Exception("DAOException...");
    }

    /* (non-Javadoc)
     * @see ua.nure.order.server.service.BookService#getBook(int  id )*
     */
    public ua.nure.order.entity.book.Book getBook(int id) throws DAOException_Exception    { 
        LOG.info("Executing operation getBook");
        System.out.println(id);
        try {
            ua.nure.order.entity.book.Book _return = new ua.nure.order.entity.book.Book();
            _return.setId(Integer.valueOf(-1840192661));
            _return.setTitle("Title-313182052");
            java.util.List<java.lang.String> _returnAuthor = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAuthorVal1 = "_returnAuthorVal-2003289306";
            _returnAuthor.add(_returnAuthorVal1);
            _return.getAuthor().addAll(_returnAuthor);
            _return.setIsbn("Isbn-1442063598");
            _return.setPrice(0.80109587373665);
            ua.nure.order.entity.book.Category _returnCategory = ua.nure.order.entity.book.Category.ACTION;
            _return.setCategory(_returnCategory);
            _return.setCount(725557376);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DAOException_Exception("DAOException...");
    }

    /* (non-Javadoc)
     * @see ua.nure.order.server.service.BookService#updateBookCount(int  id ,)int  count )*
     */
    public boolean updateBookCount(int id,int count) throws DAOException_Exception    { 
        LOG.info("Executing operation updateBookCount");
        System.out.println(id);
        System.out.println(count);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DAOException_Exception("DAOException...");
    }

    /* (non-Javadoc)
     * @see ua.nure.order.server.service.BookService#listBooks(java.lang.String  pattern )*
     */
    public java.util.List<ua.nure.order.entity.book.Book> listBooks(java.lang.String pattern) { 
        LOG.info("Executing operation listBooks");
        System.out.println(pattern);
        try {
            java.util.List<ua.nure.order.entity.book.Book> _return = new java.util.ArrayList<ua.nure.order.entity.book.Book>();
            ua.nure.order.entity.book.Book _returnVal1 = new ua.nure.order.entity.book.Book();
            _returnVal1.setId(Integer.valueOf(1594462182));
            _returnVal1.setTitle("Title1613684852");
            java.util.List<java.lang.String> _returnVal1Author = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1AuthorVal1 = "_returnVal1AuthorVal254143803";
            _returnVal1Author.add(_returnVal1AuthorVal1);
            _returnVal1.getAuthor().addAll(_returnVal1Author);
            _returnVal1.setIsbn("Isbn-1137401640");
            _returnVal1.setPrice(0.839628692173192);
            ua.nure.order.entity.book.Category _returnVal1Category = ua.nure.order.entity.book.Category.NONE;
            _returnVal1.setCategory(_returnVal1Category);
            _returnVal1.setCount(-859751825);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ua.nure.order.server.service.BookService#updateBook(ua.nure.order.entity.book.Book  book )*
     */
    public ua.nure.order.entity.book.Book updateBook(ua.nure.order.entity.book.Book book) throws DAOException_Exception    { 
        LOG.info("Executing operation updateBook");
        System.out.println(book);
        try {
            ua.nure.order.entity.book.Book _return = new ua.nure.order.entity.book.Book();
            _return.setId(Integer.valueOf(-169553908));
            _return.setTitle("Title-1073802563");
            java.util.List<java.lang.String> _returnAuthor = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAuthorVal1 = "_returnAuthorVal-2131264528";
            _returnAuthor.add(_returnAuthorVal1);
            _return.getAuthor().addAll(_returnAuthor);
            _return.setIsbn("Isbn1087315035");
            _return.setPrice(0.26013964932525124);
            ua.nure.order.entity.book.Category _returnCategory = ua.nure.order.entity.book.Category.NONE;
            _return.setCategory(_returnCategory);
            _return.setCount(-1923175824);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DAOException_Exception("DAOException...");
    }

    /* (non-Javadoc)
     * @see ua.nure.order.server.service.BookService#addBook(ua.nure.order.entity.book.Book  book )*
     */
    public ua.nure.order.entity.book.Book addBook(ua.nure.order.entity.book.Book book) throws DAOException_Exception    { 
        LOG.info("Executing operation addBook");
        System.out.println(book);
        try {
            ua.nure.order.entity.book.Book _return = new ua.nure.order.entity.book.Book();
            _return.setId(Integer.valueOf(-123725571));
            _return.setTitle("Title-1496261853");
            java.util.List<java.lang.String> _returnAuthor = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAuthorVal1 = "_returnAuthorVal-1535513314";
            _returnAuthor.add(_returnAuthorVal1);
            _return.getAuthor().addAll(_returnAuthor);
            _return.setIsbn("Isbn623326482");
            _return.setPrice(0.25209180188193814);
            ua.nure.order.entity.book.Category _returnCategory = ua.nure.order.entity.book.Category.LOVE_NOVEL;
            _return.setCategory(_returnCategory);
            _return.setCount(892201704);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DAOException_Exception("DAOException...");
    }

}
