
package ua.nure.order.server.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2016-02-17T09:48:13.796+02:00
 * Generated source version: 3.0.2
 */

@WebFault(name = "DAOException", targetNamespace = "http://service.server.order.nure.ua/")
public class DAOException_Exception extends Exception {
    
    private ua.nure.order.server.service.DAOException daoException;

    public DAOException_Exception() {
        super();
    }
    
    public DAOException_Exception(String message) {
        super(message);
    }
    
    public DAOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DAOException_Exception(String message, ua.nure.order.server.service.DAOException daoException) {
        super(message);
        this.daoException = daoException;
    }

    public DAOException_Exception(String message, ua.nure.order.server.service.DAOException daoException, Throwable cause) {
        super(message, cause);
        this.daoException = daoException;
    }

    public ua.nure.order.server.service.DAOException getFaultInfo() {
        return this.daoException;
    }
}
